### PR TITLE
Modify cudnn library versions in the documentation to reflect compatibility concerns

### PR DESCRIPTION
**Pull request by JimmyBroomfield**
The [official documentation](https://www.tensorflow.org/install/source#linux) shows the tested compatibility list for CuDNN and CUDA being CuDNN 7.4 with CUDA 10.0 for tensorflow_gpu-1.14.0.  This pull request is to update the versions in the tensorflow-gpu install page.

### CODE REVIEW

**Comment by sglvladi** [comment]
@JimmyBroomfield Thank you for your interest. The particular section of the official documentation refers to tested configurations, not strict compatibility requirements. I have done extensive work using the versioning listed in the tutorial and have not met any issues. Can you please provide some details of the compatibility issues you encountered?  

Also, the PR seems to contain a lot of other changes. Should we agree that there is a good reason to change the listed version, I will kindly request that you remove these.

**Comment by JimmyBroomfield** [comment]
Hello @sglvladi, I apologize for any extraneous changes.  These may have occurred when I did a sphinx build.  These can be rolled back.

The specific issue that I faced was related to the following error:

> Error : Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

After searching for fixes for this issue, the only solutions seemed to be finding a working combination of tensorflow, cuDNN, and CUDA.  The combination given in the tutorial did not seem to work for me, but I realize now that this might have to do with other factors including system specs.  For reference here is a list of OS/Hardware:

OS: Windows 10
CPU: AMD R7 3700X
GPU: GTX 2060

If you need more details, let me know.  The combination that I listed in the pull request work for my hardware and for tensorflow 1.14.1.

**Comment by JimmyBroomfield** [comment]
Follow up: It seems that the API has been finally updated to be compatible with tensorflow 2.0.

Here is a link for reference:

https://blog.tensorflow.org/2020/07/tensorflow-2-meets-object-detection-api.html

Also, thanks for the guide. It definitely helped me many times

**Comment by sglvladi** [comment]
> Follow up: It seems that the API has been finally updated to be compatible with tensorflow 2.0.
> 
> Here is a link for reference:
> 
> https://blog.tensorflow.org/2020/07/tensorflow-2-meets-object-detection-api.html
> 
> Also, thanks for the guide. It definitely helped me many times.
> 
> Did you want me to close the request?

Thank you for pointing this out! I wasn't aware of this 👍 I will experiment with the new version and produce a tutorial for TF 2 once I have grasped the ins and outs of the new version.

In terms of this pull request, I am somewhat hesitant on how to proceed. As I said, I have never experienced an issue and I know others who have followed the tutorial and not had incompatibility issues. I can see [here](https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-654766926) that others have reported they managed to fix the issue by updating their GPU drivers to the latest version, which is [an optional step in the tutorial](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html#update-your-gpu-drivers-optional). Do you remember if you updated your drivers upon installation of CUDA?

**Pull request closed without merging**
